Repository sullog-official/sullog-server, pull requests merged in 2023-04, with the labels that each got.

#62 카카오 로그인 flow 수정
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/alcohol/controller/AlcoholController.java
  backend/src/main/java/sullog/backend/auth/controller/AuthController.java
  backend/src/main/java/sullog/backend/auth/service/KakaoService.java
  backend/src/main/java/sullog/backend/auth/service/TokenService.java
  backend/src/main/java/sullog/backend/common/config/SecurityConfig.java
  backend/src/main/java/sullog/backend/member/config/jwt/JwtAuthFilter.java
  backend/src/main/java/sullog/backend/member/config/oauth/OAuth2SuccessHandler.java
  backend/src/main/java/sullog/backend/member/controller/AuthController.java
  backend/src/main/java/sullog/backend/member/controller/MemberController.java
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/resources/application-oauth-alpha.yml
  backend/src/main/resources/application-oauth-local.yml
  backend/src/test/java/sullog/backend/alcohol/controller/AlcoholControllerTest.java
  backend/src/test/java/sullog/backend/member/config/SecurityConfigTest.java
  backend/src/test/java/sullog/backend/member/controller/AuthControllerTest.java
  backend/src/test/java/sullog/backend/member/controller/MemberControllerTest.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: 인증

#61 [feat] 기록 피드 API
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/java/sullog/backend/record/dto/response/AllRecordMeta.java
  backend/src/main/java/sullog/backend/record/dto/response/AllRecordMetaListWithPaging.java
  backend/src/main/java/sullog/backend/record/dto/table/AllRecordMetaWithAlcoholInfoDto.java
  backend/src/main/java/sullog/backend/record/mapper/RecordMapper.java
  backend/src/main/java/sullog/backend/record/service/RecordService.java
  backend/src/main/resources/mapper/record/RecordMapper.xml
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#63 [setting] kakao 로그인 시 redirect uri 수정
  backend/src/main/resources/application-oauth-alpha.yml
  backend/src/main/resources/application-oauth-local.yml
Labels: 인증

#64 테이블 조인 시 on에 설정했던 조건들을 where로 옮김
  backend/src/main/resources/mapper/record/RecordMapper.xml
Labels: DB

#69 Access-Control-Expose-Headers 설정 추가
  backend/src/main/java/sullog/backend/common/config/SecurityConfig.java
Labels: 인증, security

#71 회원가입 시 최근검색어 필드의 기본값이 []이 되도록 수정
  backend/src/main/java/sullog/backend/auth/service/KakaoService.java
  backend/src/main/java/sullog/backend/member/entity/Member.java
Labels: 인증

#73 최근검색어 조회 시 사용자id를 알아낼 때 jwt토큰을 이용하도록 수정, api path 수정
  backend/src/main/java/sullog/backend/member/controller/MemberController.java
Labels: API

#75 [docs] v4 배포에 따른 API 문서 수정 및 테스트 코드 변경
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/member/controller/MemberControllerTest.java
Labels: api문서, 배포

#77 서버 로그파일 설정
  backend/build.gradle
  backend/src/main/java/sullog/backend/common/error/CommonControllerAdvice.java
  backend/src/main/java/sullog/backend/member/config/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/sullog/backend/record/mapper/typehandler/FlavorTagListTypeHandler.java
  backend/src/main/resources/application-alpha.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/log4j2-alpha.yml
  backend/src/main/resources/log4j2-live.yml
  backend/src/main/resources/log4j2-local.yml
Labels: 운영

#80 infra: AWS 마이그레이션 작업
  backend/src/main/resources/application-alpha.yml
  backend/src/main/resources/application-aws.yml
  backend/src/main/resources/application-live.yml
  backend/src/main/resources/application-local.yml
Labels: 인프라

#84 docs: v5 배포에 따른 API Docs 내용 수정
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
Labels: api문서

#88 fix: 경험(Record) 도메인에 별점 필드 추가, 제목 필드 삭제
  backend/src/main/java/sullog/backend/record/dto/RecordSaveRequestDto.java
  backend/src/main/java/sullog/backend/record/entity/Record.java
  backend/src/main/resources/mapper/record/RecordMapper.xml
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API, DB

#89 최근 검색어 중 특정 키워드 제거, 최근 검색어 목록 초기화 api
  backend/build.gradle
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/common/mapper/typehandler/StringListTypeHandler.java
  backend/src/main/java/sullog/backend/member/controller/MemberController.java
  backend/src/main/java/sullog/backend/member/entity/Member.java
  backend/src/main/java/sullog/backend/member/service/MemberService.java
  backend/src/test/java/sullog/backend/member/controller/MemberControllerTest.java
Labels: API

#92 deploy: v6 배포
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/alcohol/controller/AlcoholControllerTest.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: 배포

#95 jwtToken 기반 memberId 조회 로직을 인터셉터로 분리
  backend/src/main/java/sullog/backend/alcohol/controller/AlcoholController.java
  backend/src/main/java/sullog/backend/auth/controller/AuthController.java
  backend/src/main/java/sullog/backend/common/config/WebMvcConfig.java
  backend/src/main/java/sullog/backend/common/interceptor/MemberIdInterceptor.java
  backend/src/main/java/sullog/backend/member/controller/MemberController.java
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
Labels: 리팩토링

#94 JWT 토큰은 Bearer 타입만 허용하도록 수정
  backend/src/main/java/sullog/backend/alcohol/controller/AlcoholController.java
  backend/src/main/java/sullog/backend/auth/controller/AuthController.java
  backend/src/main/java/sullog/backend/auth/service/TokenService.java
  backend/src/main/java/sullog/backend/common/config/WebMvcConfig.java
  backend/src/main/java/sullog/backend/common/interceptor/MemberIdInterceptor.java
  backend/src/main/java/sullog/backend/member/controller/MemberController.java
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/test/java/sullog/backend/alcohol/controller/AlcoholControllerTest.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: 인증

#96 클라이언트 환경별 url에 따라 cors 대응
  backend/src/main/java/sullog/backend/common/config/SecurityConfig.java
  backend/src/main/resources/application-alpha.yml
  backend/src/main/resources/application-live.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/oauth-live.yml
Labels: 운영

#101 feat: 사용자 경험 통계 조회 API
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/java/sullog/backend/record/mapper/RecordMapper.java
  backend/src/main/java/sullog/backend/record/service/RecordStatisticService.java
  backend/src/main/resources/mapper/record/RecordMapper.xml
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#99 feat: 주류 도메인에 주종 필드 추가 작업
  backend/src/main/java/sullog/backend/alcohol/dto/response/AlcoholInfoDto.java
  backend/src/main/java/sullog/backend/alcohol/dto/table/AlcoholWithBrandDto.java
  backend/src/main/java/sullog/backend/alcohol/entity/Alcohol.java
  backend/src/main/java/sullog/backend/alcohol/service/AlcoholService.java
  backend/src/main/resources/mapper/alcohol/AlcoholMapper.xml
  backend/src/test/java/sullog/backend/alcohol/controller/AlcoholControllerTest.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#102 deploy: v7 배포
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
Labels: 배포

#103 fix: 경험 통계 조회 API 리스폰스에 사용자 정보 추가
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/java/sullog/backend/record/dto/response/RecordStatistics.java
  backend/src/main/java/sullog/backend/record/service/RecordStatisticService.java
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API
