Repository sullog-official/sullog-server, pull requests merged in 2023-05, with the labels that each got.

#105 경험 저장 API 요청 시 새로 추가한 데이터에 접근할 수 있도록 수정
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/java/sullog/backend/record/service/RecordService.java
  backend/src/main/resources/mapper/record/RecordMapper.xml
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: 리팩토링

#106 feat: 예외 응답 객체 작성
  backend/src/main/java/sullog/backend/alcohol/error/AlcoholControllerAdvice.java
  backend/src/main/java/sullog/backend/alcohol/error/exception/AlcoholException.java
  backend/src/main/java/sullog/backend/common/error/CommonControllerAdvice.java
  backend/src/main/java/sullog/backend/common/error/ErrorCode.java
  backend/src/main/java/sullog/backend/common/error/exception/BusinessException.java
  backend/src/main/java/sullog/backend/common/error/response/ErrorResponse.java
  backend/src/main/java/sullog/backend/member/error/MemberControllerAdvice.java
  backend/src/main/java/sullog/backend/member/error/exception/MemberException.java
  backend/src/main/java/sullog/backend/record/error/RecordControllerAdvice.java
  backend/src/main/java/sullog/backend/record/error/exception/RecordException.java
Labels: 인프라

#110 fix: UNKNOWN_ERROR를 500으로 정의하도록 enum 변경
  backend/src/main/java/sullog/backend/common/error/ErrorCode.java
  backend/src/main/java/sullog/backend/common/error/response/ErrorResponse.java
Labels: 예외

#111 deploy: v8 배포
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
Labels: 배포

#114 fix: #112 이슈에 따른 수정 작업
  backend/src/main/java/sullog/backend/alcohol/dto/response/AlcoholInfoDto.java
  backend/src/main/java/sullog/backend/alcohol/dto/table/AlcoholWithBrandDto.java
  backend/src/main/resources/static/docs/api-doc.html
  backend/src/test/java/sullog/backend/alcohol/controller/AlcoholControllerTest.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#121 깃헙액션 적용을 위한 workflow파일 추가
  .github/workflows/main.yml
Labels: 인프라, 운영

#118 키워드 기반 경험 조회 시, 조회된 경험이 없을 경우, 응답 response 에 curosr 값 임의로 추가
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#120 경험저장 api 응답 response body에 새로추가된 recordId 추가
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/java/sullog/backend/record/controller/RecordController.java
  backend/src/main/java/sullog/backend/record/dto/response/RecordSaveDto.java
  backend/src/test/java/sullog/backend/record/controller/RecordControllerTest.java
Labels: API

#124 deploy: v10 배포
  backend/src/docs/asciidoc/api-doc.adoc
  backend/src/main/resources/static/docs/api-doc.html
Labels: 배포
